name: Build Webhook Server

on:
  push:
    paths:
      - 'webhook-server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push webhook server
      run: |
        cd webhook-server
        docker build -t jes11sy/webhook-server:latest .
        docker push jes11sy/webhook-server:latest
